version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package --template-file datalake-api.yaml
                                   --s3-bucket rm-test1
                                   --s3-prefix api-code
                                   --output-template-file petstore-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/datalake-api-output.yaml
